coverage:
  range: "97...100"
  round: down
  precision: 2
  status:
    project:
      default:
        target: auto
        threshold: 3%
        base: auto
        branches:
          - master
          - dev
        if_ci_failed: error
        informational: false
        only_pulls: true
        removed_code_behavior: adjust_base

comment:
  layout: " diff, flags, files"
  behavior: default
  require_changes: false
  require_base: false
  require_head: false
