name: PHPunit

on: [ push ]

# Cancels all previous workflow runs for the same branch that have not yet completed.
concurrency:
    # The concurrency group contains the workflow name and the branch name.
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

jobs:
    phpunit:
        runs-on: ${{ matrix.os }}
        strategy:
            fail-fast: false
            matrix:
                os: [ ubuntu-latest ]
                # When you change a version here, change it also in the SonarCloud if condition
                php: [ '8.3', '8.4' ]

        steps:
            -   name: Checkout
                uses: actions/checkout@v4

            -   name: Setup PHP
                uses: shivammathur/setup-php@2.32.0
                with:
                    php-version: ${{ matrix.php }}
                    coverage: pcov
                    extensions: ast

            -   name: Get Composer Cache Directory
                id: composer-cache
                run: |
                    echo "::set-output name=dir::$(composer config cache-files-dir)"

            -   name: Cache Composer's dependencies
                uses: actions/cache@v4
                with:
                    path: ${{ steps.composer-cache.outputs.dir }}
                    key: php-composer-dependencies-cache

            -   name: Install Composer deps
                uses: ramsey/composer-install@v3
                with:
                    composer-options: --no-scripts

            -   name: Install Composer bin PHPUnit
                uses: ramsey/composer-install@v3
                with:
                    working-directory: './vendor-bin/phpunit'

            -   name: Install Composer bin Infection
                uses: ramsey/composer-install@v3
                with:
                    working-directory: './vendor-bin/infection'

            -   name: Run PHPunit
                run: |
                    ./vendor-bin/phpunit/vendor/bin/phpunit --coverage-clover ./var/coverage/clover.xml --coverage-xml ./var/coverage/coverage-xml --log-junit ./var/coverage/junit.xml

            -   name: Run Infection
                if: |
                    matrix.php == '8.3'
                run: |
                    ./vendor-bin/infection/vendor/bin/infection --coverage=./var/coverage --min-msi=100 --min-covered-msi=100

            -   name: Upload coverage reports to Codecov
                if: matrix.php == '8.3' && contains(github.ref, 'master')
                uses: codecov/codecov-action@v5
                env:
                    CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
                with:
                    fail_ci_if_error: false
                    verbose: true
                    files: ./var/coverage/clover.xml

            -   name: Change paths in clover.xml
                run: |
                    sed -i 's+/home/runner/work/monolog-html-line-formatter/monolog-html-line-formatter+/github/workspace+g' ./var/coverage/clover.xml

            -   name: Sonarcloud
                if: |
                    github.ref == 'refs/heads/dev' && matrix.php == '8.3'
                uses: SonarSource/sonarqube-scan-action@v5.1.0
                env:
                    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                    SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
